// import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <h1 style={
          { backgroundColor: "yellow", paddingTop: "20px", paddingBottom: "20px", paddingLeft: "10px", paddingRight: "10px" }
        }>
          App common layout
        </h1>
        {children}
      </body>
    </html>
  )
}
